[package]
name = "ptah-render"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
ptah-core = { path = "../ptah-core" }
jiff = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
getrandom = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
